---
- name: Install vdsm-prometheus COPR repo on EPEL
  get_url: url={{ vdsm_prometheus_epel_repo_url }} dest=/etc/yum.repos.d/vdsm-prometheus.repo
  retries: 5
  delay: 10
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Install vdsm-prometheus COPR repo on Fedora
  get_url: url={{ vdsm_prometheus_fedora_repo_url }} dest=/etc/yum.repos.d/vdsm-prometheus.repo
  retries: 5
  delay: 10
  when: ansible_distribution == 'Fedora'

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ vdsm_prometheus_repo_gpg_key_url }}"
    state: present

