---
galaxy_info:
  author: Roman Mohr
  description: Install vdsm-prometheus COPR repository
  license: GPLv3
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 7
  - name: Fedora
    versions:
    - 22
    - 23
  categories:
  - packaging
